### PR TITLE
Fix #70

### LINKED ISSUE #70: Removing a tag from a page doesn't remove the page from the list where it's displayed
Using GetContentReferencesByTags on an article list page to show any articles with the same tag.

Steps to reproduce:

1. Find/create Article list page and Article Page(s) that have common tags
2. Remove the common tag from Article Page(s) and publish
3. Check resulting Article page list.
4. The page is still there.

(On the other hand, adding a new tag, instantly works - shows the page).

Running Maintenance scheduled job doesn't help.

The site is available only in Norwegian.

### PR DESCRIPTION
**Pull request by mariajemaria**
Now, all localizable content should have the group key set (populated with master language code), without TagsGroupKeyAttribute or CultureSpecificAttribute specified

### CODE REVIEW

File: src/Helpers/TagsHelper.cs [hunk 1]
```diff
@@ -36,8 +41,8 @@ public static ContentReference GetContentReference(Guid contentGuid)
 
         public static bool IsTagProperty(PropertyDefinition propertyDefinition)
         {
-            return propertyDefinition != null
-                   && propertyDefinition.TemplateHint == "Tags";
+            return propertyDefinition != null &&
```
Comment (marisks) [inline src/Helpers/TagsHelper.cs]: `&&` is more visible when is on the new line as before.

File: src/EditorDescriptors/GetaTagsAttribute.cs [hunk 2]
```diff
@@ -35,18 +38,20 @@ public virtual void OnMetadataCreated(ModelMetadata metadata)
                 return;
             }
 
+
```
Comment (marisks) [inline src/EditorDescriptors/GetaTagsAttribute.cs]: Remove unnecessary empty line.

File: src/EditorDescriptors/GetaTagsAttribute.cs [hunk 3]
```diff
@@ -1,10 +1,12 @@
-﻿using System;
-using System.Linq;
-using System.Web.Mvc;
+﻿using EPiServer.Cms.Shell.Extensions;
 using EPiServer.DataAnnotations;
 using EPiServer.Shell;
 using EPiServer.Shell.ObjectEditing;
 using Geta.Tags.Attributes;
+using Geta.Tags.Helpers;
```
Comment (marisks) [inline src/EditorDescriptors/GetaTagsAttribute.cs]: Are all usings in use? Please check in other modified files too.

Comment (mariajemaria) [reply src/EditorDescriptors/GetaTagsAttribute.cs]: All usings are in use, they were inline, so I didn't like that and changed.

File: src/Helpers/TagsHelper.cs (hunk 1 above)
Comment (mariajemaria) [reply src/Helpers/TagsHelper.cs]: My eyes hurt, but np.

**Comment by mariajemaria** [comment]
@marisks, all don, thx for the comments!
